# Generated by Django 4.2.4 on 2024-01-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_country_project_published_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
