# Generated by Django 4.2.4 on 2024-01-15 13:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_country_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='address',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='published_countries',
        ),
        migrations.AddField(
            model_name='author',
            name='email_address',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(default='', validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='excerpt',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='image_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='blog.author'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='blog.tag'),
        ),
    ]
